- name: Add PostgreSQL client
  yum:
    name: postgresql
    state: present
  when: ansible_os_family == 'RedHat'

- name: Check IDO database exists
  shell: psql {{ icinga2_ido_pg_db }} -c 'SELECT COUNT(1) FROM icinga_instances';
  environment:
    PGPASSWORD: '{{ icinga2_ido_pg_password }}'
    PGUSER: '{{ icinga2_ido_pg_user }}'
    PGHOST: '{{ icinga2_ido_pg_host }}'
    PGAPPNAME: 'ansible-ido-setup'
  check_mode: no
  register: _ido_result
  changed_when: False
  failed_when: "'FATAL' in _ido_result.stderr"

- name: Create IDO pg_database tables
  shell: psql {{ icinga2_ido_pg_db }} -f /usr/share/icinga2-ido-pgsql/schema/pgsql.sql
  environment:
    PGPASSWORD: '{{ icinga2_ido_pg_password }}'
    PGUSER: '{{ icinga2_ido_pg_user }}'
    PGHOST: '{{ icinga2_ido_pg_host }}'
    PGAPPNAME: 'ansible-ido-setup'
  when: "'does not exist' in _ido_result.stderr"
